displayErrorDetails: true
addContentLengthHeader: false

# constants for PHP code
log_errors: true
debug: {DEBUG}

db:
  adapter: {DB_ADAPTER}
  host: {DB_HOST}
  port: {DB_PORT}
  database: {DB_DATABASE}
  user: {DB_USER}
  password: {DB_PASSWORD}

# validation
password_min: 5
login_min: 3
login_max: 20

# auth
# 1..16 digits
captcha_digits: 2
# in hours
token_ttl: 168

# folders for PHP code
folders:
  root: {ROOT_PATH}

logger:
  name: pc-associ
  path: {LOG_PATH}

event_log:
  name: pc-event-log
  path: {EVENT_LOG_PATH}

view:
  templates_path:
    - /../views/
    - {PLASTICODE_TEMPLATES_PATH}
  cache_path: false

associations:
  approval_threshold: 2
  mature_threshold: 2
  coeffs:
    usage: 1
    dislike: 1
  # sidebar limit
  last_added_limit: 10

languages:
  default_id: 1

news:
  latest_limit: 5

  users:
  mature_age: 16

words:
  approval_threshold: 1
  mature_threshold: 2
  coeffs:
    approved_association: 1
    dislike: 1
  # sidebar limit
  last_added_limit: 10

yandex_dict:
  key: {YANDEX_DICT_KEY}
  word_ttl_days: 30

telegram:
  bot_name: AssociRuBot
  bot_token: {TELEGRAM_BOT_TOKEN}

jobs:
  update_associations:
    ttl_min: 1440
    batch_size: 500
  update_words:
    ttl_min: 1440
    batch_size: 500
  load_unchecked_dict_words:
    batch_size: 10
  match_dangling_dict_words:
    ttl_min: 10
    batch_size: 10
